# Site settings
title:       Objectivement objectif.
author:      Quentin Pautrat
description: "Pot-pourri d'idées, de pensées, de connaissances, de critiques. Développeur et passionné j'essaye de partager de façon objective diverses expériences. Développement, internet, cinéma, jeux, etc..."
baseurl:     ""
url:         "http://qpautrat.github.io"

# Google analytics
google_analytics: UA-49889834-2

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: false
github_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Objectivement, tu <u>dois</u> partager'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     5
sass:
  compressed: true
