# Site settings
title:       Objectivement objectif.
author:      Quentin Pautrat
description: "Software craftsman"
url:         "http://qpautrat.github.io"

# Google analytics
google_analytics: UA-49889834-2

plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-sitemap
  - jemoji
  - jekyll-github-metadata

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
show_social_icons: true
github_username: qpautrat
stackoverflow_id:
twitter_username: qpautrat
google_plus_id:
linkedin_username: qpautrat
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Objectivement, tu <u>dois</u> partager'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false

# Build settings
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     5
sass:
  compressed: true

encoding: utf-8

languages: ["fr", "en"]
exclude_from_localizations: ["images", "css", "assets"]